### Question 1

In this question, we will use Monte Carlo (MC) simulations to simulate the power function π(λ,k), and compute the asymptotic power of the Wald test for different values of λ and k. Assume that α=0.05.

######  First Load in the necesary libraries

In [42]:
using Plots, LaTeXStrings, Distributions


<u> Part A </u>

In [43]:
function power(λ,k, R)
    Z = randn(R,k)
    X = (Z[:, 1].+ λ).^2 + sum(Z[:,2:k].^2, dims =2)
    π = sum(X.> quantile(Chisq(k),0.95))/R
    return π
end

power (generic function with 1 method)

In [44]:
K = [1,5,10]
Λ = 0.0:0.1:6.0
Powers = zeros(length(Λ), length(K))
for i in 1 : length(Λ)
    for j in 1: length(K)
        Powers[i,j] = power(Λ[i], K[j], 10^5)
    end
end
Powers

61×3 Matrix{Float64}:
 0.05117  0.05005  0.05058
 0.0513   0.05134  0.05076
 0.05535  0.0517   0.05162
 0.06146  0.05263  0.05216
 0.06792  0.05671  0.05384
 0.0792   0.06183  0.0579
 0.09071  0.06705  0.06089
 0.10585  0.07105  0.06488
 0.126    0.07871  0.07097
 0.14802  0.08825  0.07554
 0.16912  0.09995  0.08248
 0.19581  0.1096   0.09043
 0.22208  0.12315  0.09825
 ⋮                 
 0.99848  0.98016  0.94642
 0.99883  0.98519  0.95533
 0.99914  0.98846  0.96331
 0.99931  0.99104  0.97023
 0.99952  0.99265  0.97649
 0.99966  0.99437  0.98031
 0.99978  0.99586  0.98401
 0.99989  0.99679  0.9881
 0.99994  0.99749  0.99033
 0.99993  0.99829  0.9926
 0.99995  0.99874  0.9946
 0.99997  0.9991   0.99587

<u >Part B </u>

What are the simulated probabilities of rejection when λ=0? Are the they close to what one would expect?

In [51]:
K = [1,5,10]
Λ = 0.0
Powers = zeros(3)
for i in 1 : 3
    Powers[i] = power(Λ, K[i], 10^5)
end
Powers

3-element Vector{Float64}:
 0.04995
 0.04975
 0.04847

In [46]:
A = [2 3 3;4 3 5;5 4 4; 3 -3 4]
sum(A[:,2:3].^2, dims = 2)

4×1 Matrix{Int64}:
 18
 34
 32
 25

In [47]:
X = [1,2,5]
X.>1.5

3-element BitVector:
 0
 1
 1